#!/usr/bin/env python3
import atexit
import logging

from gi.repository import GObject
from roberta.lab import Service

LOG_PATH = '/var/log/robot/roberta.log'

logging.basicConfig(filename = LOG_PATH, level = logging.DEBUG)
logger = logging.getLogger('roberta')

GObject.threads_init()
service = None


def cleanup():
    global service

    if service:
        service.hal.stopAllMotors()
    logger.info('--- done ---')
    logging.shutdown()


def main():
    global service

    logger.info('--- starting ---')

    atexit.register(cleanup)

    loop = GObject.MainLoop()
    service = Service('/org/openroberta/Lab1')
    logger.debug('loop running')
    loop.run()

if __name__ == "__main__":
    main()
